
name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOCKER_USER: samueltallet
  DOCKER_REPO: mongodb-php-gui

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: docker login
      run: |
        docker login -u ${{ env.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        
    - name: docker build
      run: docker build . --file Dockerfile --tag ${{ env.DOCKER_USER }}/${{ env.DOCKER_REPO }}:latest
      
    - name: docker push
      run: docker push ${{ env.DOCKER_USER }}/${{ env.DOCKER_REPO }}:latest
